name: prism-all-in-one-ai-chat

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: prismuser
      POSTGRES_PASSWORD: prismpassword
      POSTGRES_DB: prismdb
    ports:
      - "5432:5432"
    restart: always
